extends "res://tests/live_checkpoint.gd"
const Chapter = preload("res://scripts/first_chapter.gd")
func run() -> void:
	var g := fixture()
	g.start_panel.hide()
	g._show_tray("goals")
	var before: String = JSON.stringify(g.Save.capture(g).runtime)
	for i in range(10): Chapter.current(g)
	check(before == JSON.stringify(g.Save.capture(g).runtime), "Guidance never designates, schedules or supplies resources")
	check(Chapter.current(g).completed == 0, "Logistics guidance adds no invented milestone")
	g.hud.chapter_support.pressed.emit()
	check(g.active_tray == "local_harvest", "Initial support opens actual harvest commands")
	g.local_harvest.set_active(2, true)
	g.local_harvest.set_active(4, true)
	g._show_tray("goals")
	check("22 bois et 18 fibres" in Chapter.current(g).text, "Unregulated sources receive reserve guidance")
	g.hud.chapter_support.pressed.emit()
	check(g.active_tray == "harvest_targets", "Second support opens targets")
	check(g.local_harvest.targets.wood == -1 and g.local_harvest.targets.fiber == -1, "Recommendations never apply settings silently")
	g.local_harvest.set_target("wood", 5)
	g.local_harvest.set_target("fiber", 7)
	g.torches.add_item(g.depots.entry(0), 180, "lantern")
	g._show_tray("goals")
	g.hud.chapter_support.pressed.emit()
	check(g.active_tray == "lantern_service", "Existing lantern offers maintenance guidance")
	check(g.local_harvest.targets.wood == 5 and g.local_harvest.targets.fiber == 7, "Custom targets are respected")
	g.torches.set_refill_target(2)
	g._show_tray("goals")
	g.hud.chapter_support.pressed.emit()
	check(g.active_tray == "harvest_targets", "Configured logistics leads to reserve diagnostics")
	g._choose_build("workshop")
	g._place_build(Vector3(0, 0, -3))
	g._show_tray("goals")
	g.hud.chapter_support.pressed.emit()
	check(g.active_tray == "lantern_production" and g.torches.craft_target == 0, "Workshop offers production guidance without changing target")
	g.torches.set_craft_target(1)
	check(Chapter.logistics(g).tray == "harvest_targets", "Custom equipment target is respected")
	var copy := clone(g, "chapter logistics support")
	if copy != null:
		check(Chapter.current(copy) == Chapter.current(g), "Support derives identically from restored simulation")
		copy.queue_free()
	g.queue_free()
	await process_frame
	print("CHAPTER_LOGISTICS: %d failure(s)" % failures)
	quit(1 if failures else 0)
