"""Build the standalone reference catalogue; generated PNGs remain unmodified."""
from pathlib import Path
import html
import json

ROOT = Path(__file__).resolve().parents[1]
FOLDER = ROOT / 'docs' / 'catalogue-assets-v01'

def build():
    data = json.loads((FOLDER / 'prompts.json').read_text(encoding='utf-8'))
    boards = data['boards']
    cards = []
    for board in boards:
        image = f"images/{board['n']}-{board['slug']}.png"
        escape = html.escape
        tags = ''.join(f'<span>{escape(code)}</span>' for code in board['ids'])
        search = ' '.join([board['title'], board['family'], board['notes'], *board['ids']])
        cards.append(f'''<article class="card" data-family="{escape(board['family'])}" data-search="{escape(search)}">
          <button class="picture" data-src="{image}" data-title="{escape(board['title'])}" aria-label="Agrandir : {escape(board['title'])}">
            <img src="{image}" alt="Planche {board['n']} : {escape(board['title'])}, vues et détails de référence" loading="lazy" width="1536" height="1024">
            <span class="zoom">Agrandir ↗</span>
          </button>
          <div class="card-copy"><div class="eyebrow">{board['n']} / {escape(board['family'])}</div>
            <h2>{escape(board['title'])}</h2><div class="status">{escape(board['status'])}</div>
            <p>{escape(board['notes'])}</p><div class="tags">{tags}</div>
            <a class="original" href="{image}" target="_blank" rel="noopener">Ouvrir l’image originale ↗</a>
          </div></article>''')
    template = r'''<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sous le Plancher — Catalogue des assets</title>
<style>
:root{color-scheme:dark;--bg:#171a18;--panel:#222622;--ink:#f0ebdf;--muted:#b7b9ac;--gold:#d4b478;--line:#41473e}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Segoe UI,Arial,sans-serif;line-height:1.6}button,input,a{font:inherit}button,a,input{touch-action:manipulation}a{color:var(--gold)}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid var(--gold);outline-offset:5px}
.wrap{max-width:1450px;margin:auto;padding:0 48px}.masthead{padding:24px 0;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;font-size:12px;letter-spacing:.15em;text-transform:uppercase}.masthead a{text-decoration:none;color:var(--ink)}.eyebrow{color:var(--gold);font-size:12px;text-transform:uppercase;letter-spacing:.15em;font-weight:600}
header{padding:66px 0 44px;display:grid;grid-template-columns:1fr 240px;gap:48px}h1{font:normal clamp(40px,5vw,70px)/1.08 Georgia,serif;margin:18px 0 24px;letter-spacing:-.035em}header p{max-width:760px;color:var(--muted);font-size:18px;margin:0}.edition{align-self:end;border-left:1px solid var(--line);padding-left:32px;color:var(--muted);font-size:14px}.edition strong{display:block;color:var(--gold);font:normal 100px/1 Georgia,serif}.edition span{display:block;margin-top:12px}
.direction{display:grid;grid-template-columns:repeat(3,1fr);border-block:1px solid var(--line);gap:32px;padding:26px 0 30px;margin-bottom:36px}.direction h2{font:normal 23px Georgia,serif;margin:0 0 8px}.direction p{font-size:14px;color:var(--muted);margin:0}
.toolbar{display:flex;justify-content:space-between;gap:16px;align-items:center;flex-wrap:wrap;margin:30px 0 12px}.filters{display:flex;gap:8px;flex-wrap:wrap}.filters button,.modal-button{background:transparent;border:1px solid var(--line);border-radius:30px;color:var(--ink);padding:9px 17px}.filters button[aria-pressed=true]{background:var(--gold);border-color:var(--gold);color:#171a18}.search{border:1px solid var(--line);border-radius:7px;background:var(--panel);padding:10px 15px;color:var(--ink);width:270px;max-width:100%}.counter{font-size:13px;color:var(--muted);margin:0 0 24px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:30px}.card{background:var(--panel);border:1px solid var(--line);border-radius:8px;overflow:hidden}.card[hidden]{display:none}.picture{display:block;width:100%;border:0;padding:0;position:relative;background:#d5d0c5}.picture img{width:100%;height:auto;aspect-ratio:3/2;object-fit:contain;display:block}.zoom{position:absolute;right:12px;bottom:12px;padding:5px 12px;background:#171a18df;border-radius:20px;color:var(--ink);font-size:12px}.card-copy{padding:24px 27px 25px}.card h2{font:normal 31px/1.15 Georgia,serif;margin:10px 0}.status{color:var(--gold);font-size:13px}.card p{color:var(--muted);font-size:14px;margin:16px 0;max-width:65ch}.tags{display:flex;flex-wrap:wrap;gap:7px}.tags span{font-size:11px;padding:3px 7px;border:1px solid var(--line);border-radius:3px;color:var(--muted)}.original{display:inline-block;margin-top:18px;font-size:13px;text-underline-offset:4px}.empty{padding:35px;border:1px dashed var(--line);color:var(--muted)}
.production{margin:60px 0 40px;padding:30px;border:1px solid var(--line);border-left:3px solid var(--gold);border-radius:5px}.production h2{font:normal 29px Georgia,serif;margin:0 0 15px}.production p,.production li{font-size:14px;color:var(--muted)}.production ul{padding-left:20px;columns:2;column-gap:50px}.production li{break-inside:avoid;margin-bottom:12px}footer{display:flex;justify-content:space-between;gap:25px;padding:24px 0 35px;border-top:1px solid var(--line);font-size:12px;color:var(--muted)}
dialog{width:96vw;max-width:1800px;max-height:96vh;background:#151815;border:1px solid var(--line);padding:16px;color:var(--ink);border-radius:8px}dialog::backdrop{background:#000d}.modal-head{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:10px}.modal-head h2{font:normal 24px Georgia,serif;margin:0}.modal-controls{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.modal-button{padding:5px 14px}.image-stage{overflow:auto;max-height:79vh;display:block;text-align:center;background:#d5d0c5}.image-stage img{display:block;max-width:100%;max-height:79vh;width:auto;height:auto;margin:auto}.image-stage.actual img{max-width:none;max-height:none;width:auto;height:auto}.modal-note{font-size:12px;color:var(--muted);margin:8px 0 0}.visually-hidden{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
@media(max-width:850px){.wrap{padding:0 20px}header{grid-template-columns:1fr;padding-top:36px;gap:25px}.edition{display:none}.direction{grid-template-columns:1fr;gap:20px}.grid{grid-template-columns:1fr}.production ul{columns:1}.modal-head{align-items:start;flex-direction:column}.masthead{font-size:10px}.search{width:100%}footer{flex-direction:column}}
@media print{:root{--bg:white;--panel:white;--ink:#222;--muted:#444;--gold:#745728;--line:#ccc}body{background:white;color:#222}.wrap{padding:0}.toolbar,.counter,.zoom,.original,dialog{display:none!important}header{padding:10px 0}.edition{display:none}.grid{display:block}.card,.card[hidden]{display:block;break-inside:avoid;page-break-before:always;border:0}.card-copy{padding:12px 0}.picture img{max-height:65vh}.direction,.production{break-inside:avoid}footer a{color:#444}}
</style></head><body><div class="wrap">
<div class="masthead"><a href="#">Sous le Plancher</a><span>Direction artistique / Catalogue V01</span></div>
<header><div><div class="eyebrow">Références pour la création 3D</div><h1>Un petit monde.<br>Des objets qui racontent.</h1><p>Habitants, faune et objets récupérés : des planches à examiner ensemble pour donner une matière, une silhouette et une logique de fabrication à la vie sous le plancher.</p></div><div class="edition"><strong>12</strong><span>planches originales<br>4 familles d’assets<br>Propositions à commenter</span></div></header>
<section class="direction" aria-label="Direction artistique"><div><h2>Humains minuscules</h2><p>Des adultes lisibles et expressifs, du tissu récupéré et des tenues réparées. Une stylisation mesurée, sans proportions de poupée.</p></div><div><h2>Matières vécues</h2><p>Bois fendu, coton grossier, cuir usé, mica et métal terni. Les traces d’usage suivent la construction de chaque objet.</p></div><div><h2>Des vues pour construire</h2><p>Angles complémentaires, détails d’attache et états utiles. Un éclairage neutre révèle les formes ; l’ambiance sombre revient dans le jeu.</p></div></section>
<nav class="toolbar" aria-label="Filtrer le catalogue"><div class="filters"><button aria-pressed="true" data-filter="Tous">Tout voir</button><button aria-pressed="false" data-filter="Habitants">Habitants</button><button aria-pressed="false" data-filter="Faune">Faune</button><button aria-pressed="false" data-filter="Objets">Objets</button><button aria-pressed="false" data-filter="Habitat">Habitat</button></div><label class="visually-hidden" for="search">Rechercher un asset</label><input id="search" class="search" type="search" placeholder="Rechercher : lit, fourmi, CHR-01…"></nav>
<p class="counter" aria-live="polite">12 planches affichées — cliquer sur une image pour l’agrandir.</p>
<main class="grid" id="catalogue">__CARDS__</main><p class="empty" hidden>Aucune planche ne correspond. Changez de famille ou effacez la recherche.</p>
<section class="production"><div class="eyebrow">De la référence au modèle</div><h2>Ce que nous fixerons avant Blender</h2><p>Ces images sont des propositions artistiques. Elles ne remplacent pas les assets actuels et ne valident pas de nouvelles mécaniques de jeu. Les espèces optionnelles restent identifiées comme exploratoires.</p><ul><li>Choisir les silhouettes et matériaux à retenir ; signaler les éléments à simplifier ou à reprendre.</li><li>Fixer les dimensions contre l’habitant et les animations existantes. Les objets et espèces de différentes planches ne sont pas à la même échelle.</li><li>Recouper les vues générées : nombre de membres, coutures, raccords et attaches peuvent varier. Elles ne constituent pas des plans cotés.</li><li>Modéliser dans Blender : volumes, topologie, UV, matériaux et points d’interaction, puis vérifier le rig et les collisions dans Godot.</li><li>Séparer le corps, les vêtements, les accessoires et les charges lorsque leur usage l’exige ; garder le sac centré et les mains disponibles.</li><li>Évaluer la lecture à distance et les budgets du cahier des charges. Les microdétails de ces images ne seront pas tous modélisés.</li></ul></section>
<footer><span>Sous le Plancher · Références visuelles V01 · À valider</span><span><a href="README.md">Notes de production</a> · <a href="prompts.json">Prompts et provenance</a> · Générateur intégré, version non attestée</span></footer>
</div>
<dialog aria-labelledby="modal-title"><div class="modal-head"><h2 id="modal-title"></h2><div class="modal-controls"><button class="modal-button" id="previous" aria-label="Planche précédente">←</button><button class="modal-button" id="next" aria-label="Planche suivante">→</button><button class="modal-button" id="zoom" aria-pressed="false">Taille réelle</button><a id="download" class="modal-button" download>PNG original</a><button class="modal-button" id="close">Fermer ×</button></div></div><div class="image-stage"><img id="full-image" alt=""></div><p class="modal-note">Flèches : changer de planche · Échap : fermer · Taille réelle : examiner les détails</p></dialog>
<script>
const cards=[...document.querySelectorAll('.card')], filters=[...document.querySelectorAll('[data-filter]')];
const search=document.querySelector('#search'); let family='Tous';
const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function filter(){const q=normalize(search.value);let count=0;for(const card of cards){card.hidden=!((family==='Tous'||card.dataset.family===family)&&normalize(card.dataset.search).includes(q));if(!card.hidden)count++;}document.querySelector('.counter').textContent=count+' planche'+(count>1?'s':'')+' affichée'+(count>1?'s':'')+' — cliquer sur une image pour l’agrandir.';document.querySelector('.empty').hidden=count!==0;}
filters.forEach(b=>b.addEventListener('click',()=>{family=b.dataset.filter;filters.forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();}));search.addEventListener('input',filter);
const modal=document.querySelector('dialog'), stage=document.querySelector('.image-stage'), zoom=document.querySelector('#zoom');let current=0;
function visible(){return cards.filter(c=>!c.hidden).map(c=>c.querySelector('.picture'));}
function show(index){const items=visible();current=(index+items.length)%items.length;const item=items[current];document.querySelector('#modal-title').textContent=item.dataset.title;const img=document.querySelector('#full-image');img.src=item.dataset.src;img.alt=item.getAttribute('aria-label').replace('Agrandir : ','');document.querySelector('#download').href=item.dataset.src;stage.classList.remove('actual');zoom.setAttribute('aria-pressed','false');zoom.textContent='Taille réelle';}
document.querySelectorAll('.picture').forEach(b=>b.addEventListener('click',()=>{show(visible().indexOf(b));modal.showModal();}));document.querySelector('#close').onclick=()=>modal.close();document.querySelector('#previous').onclick=()=>show(current-1);document.querySelector('#next').onclick=()=>show(current+1);zoom.onclick=()=>{const actual=stage.classList.toggle('actual');zoom.setAttribute('aria-pressed',String(actual));zoom.textContent=actual?'Adapter à l’écran':'Taille réelle';};modal.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();show(current-1);}if(e.key==='ArrowRight'){e.preventDefault();show(current+1);}});
</script></body></html>'''
    (FOLDER / 'index.html').write_text(template.replace('__CARDS__', '\n'.join(cards)), encoding='utf-8')
    print(f'Catalogue built: {len(boards)} boards -> {FOLDER / "index.html"}')

if __name__ == '__main__':
    build()
