"""Bake generated surface atlases into portable glTF material maps in Blender.

Albedo images are generated by image_gen. The normal maps are shallow relief
estimates baked from luminance, not measured physical surface scans.
"""
import bpy
from pathlib import Path


def atlas_material(name, atlas, region, tint, roughness, metallic, relief, folder, size=768):
    folder = Path(folder)
    color_path = folder / (name + '_basecolor.png')
    normal_path = folder / (name + '_normal.png')
    if not color_path.exists() or not normal_path.exists():
        scene = bpy.context.scene
        scene.render.engine = 'CYCLES'
        scene.cycles.samples = 1
        scene.render.threads_mode = 'FIXED'
        scene.render.threads = 6
        bpy.ops.mesh.primitive_plane_add(size=2)
        plane = bpy.context.object
        work = bpy.data.materials.new(name + '_bake')
        work.use_nodes = True
        plane.data.materials.append(work)
        nodes = work.node_tree.nodes
        links = work.node_tree.links
        nodes.clear()
        output = nodes.new('ShaderNodeOutputMaterial')
        uv = nodes.new('ShaderNodeTexCoord')
        mapping = nodes.new('ShaderNodeMapping')
        mapping.inputs['Location'].default_value = (region[0], region[1], 0)
        mapping.inputs['Scale'].default_value = (region[2], region[3], 1)
        links.new(uv.outputs['UV'], mapping.inputs['Vector'])
        image = nodes.new('ShaderNodeTexImage')
        image.image = bpy.data.images.load(str(atlas), check_existing=True)
        links.new(mapping.outputs['Vector'], image.inputs['Vector'])
        multiply = nodes.new('ShaderNodeMixRGB')
        multiply.blend_type = 'MULTIPLY'
        multiply.inputs[0].default_value = 1
        multiply.inputs[2].default_value = (*tint, 1)
        links.new(image.outputs['Color'], multiply.inputs[1])
        emit = nodes.new('ShaderNodeEmission')
        links.new(multiply.outputs[0], emit.inputs[0])
        links.new(emit.outputs[0], output.inputs['Surface'])
        target = nodes.new('ShaderNodeTexImage')
        color = bpy.data.images.new(name+'_basecolor',width=size,height=size)
        target.image = color
        nodes.active = target
        scene.render.bake.margin = 2
        bpy.ops.object.bake(type='EMIT')
        color.filepath_raw = str(color_path)
        color.file_format = 'PNG'
        color.save()
        normal = bpy.data.images.new(name+'_normal',width=size,height=size)
        normal.colorspace_settings.name = 'Non-Color'
        target.image = normal
        nodes.active = target
        bsdf = nodes.new('ShaderNodeBsdfPrincipled')
        bump = nodes.new('ShaderNodeBump')
        bump.inputs['Strength'].default_value = .28
        bump.inputs['Distance'].default_value = relief
        links.new(image.outputs['Color'], bump.inputs['Height'])
        links.new(bump.outputs['Normal'], bsdf.inputs['Normal'])
        links.new(bsdf.outputs[0], output.inputs['Surface'])
        bpy.ops.object.bake(type='NORMAL')
        normal.filepath_raw = str(normal_path)
        normal.file_format = 'PNG'
        normal.save()
        bpy.data.objects.remove(plane, do_unlink=True)
        bpy.data.materials.remove(work)
    material = bpy.data.materials.new(name)
    material.use_nodes = True
    material.diffuse_color = (*tint, 1)
    nodes = material.node_tree.nodes
    links = material.node_tree.links
    bsdf = nodes.get('Principled BSDF')
    bsdf.inputs['Roughness'].default_value = roughness
    bsdf.inputs['Metallic'].default_value = metallic
    color = nodes.new('ShaderNodeTexImage')
    color.image = bpy.data.images.load(str(color_path),check_existing=True)
    links.new(color.outputs['Color'], bsdf.inputs['Base Color'])
    normal = nodes.new('ShaderNodeTexImage')
    normal.image = bpy.data.images.load(str(normal_path),check_existing=True)
    normal.image.colorspace_settings.name = 'Non-Color'
    normal_map = nodes.new('ShaderNodeNormalMap')
    links.new(normal.outputs['Color'], normal_map.inputs['Color'])
    links.new(normal_map.outputs['Normal'], bsdf.inputs['Normal'])
    return material


def create_materials(folder):
    folder = Path(folder)
    surfaces = folder / 'materials_atlas.png'
    matchbox = folder / 'matchbox_atlas.png'
    assert surfaces.exists() and matchbox.exists(), 'Generated source atlases required'
    definitions = {
        'linen_shirt': (surfaces,(.5,.5,.5,.5),(1,1,.95),.92,0,.008),
        'sage_canvas': (surfaces,(.5,.5,.5,.5),(.36,.55,.37),.94,0,.008),
        'charcoal_trousers': (surfaces,(.5,.5,.5,.5),(.15,.19,.19),.94,0,.006),
        'rust_patch': (surfaces,(.5,.5,.5,.5),(.65,.26,.13),.93,0,.008),
        'worn_leather': (surfaces,(0,0,.5,.5),(.8,.7,.6),.73,0,.008),
        'old_wood': (surfaces,(0,.5,.5,.5),(.8,.8,.76),.88,0,.014),
        'cut_wood': (surfaces,(0,.5,.5,.5),(1.1,1.05,.92),.85,0,.01),
        'cardboard': (matchbox,(.5,0,.5,.5),(1,1,1),.97,0,.004),
        'faded_paper': (matchbox,(.5,0,.5,.5),(1.2,1.17,1.05),.96,0,.002),
        'tarnished_brass': (surfaces,(.5,0,.5,.5),(1,.96,.84),.66,.65,.006),
        'matchbox_print': (matchbox,(0,.5,1,.5),(1,1,1),.94,0,.0005),
        'matchbox_striker': (matchbox,(0,0,.5,.5),(1,1,1),.98,0,.006),
    }
    return {name:atlas_material(name,*definition,folder,size=1024 if name in ['old_wood','cut_wood','matchbox_print'] else 768)
            for name,definition in definitions.items()}
